language: python
dist: xenial
sudo: required

python:
  - "3.7"

env:
  - VIM_TYPE=vim
  - VIM_TYPE=nvim

install:
  - git clone https://github.com/junegunn/vader.vim.git
  - pip install vim-vint
  - |
    if [[ $VIM_TYPE == nvim ]]; then
      sudo add-apt-repository ppa:neovim-ppa/stable -y
    fi
  - sudo apt-get update -q
  - |
    if [[ $VIM_TYPE == vim ]]; then
      sudo apt-get install -y vim
      vim --version
    fi
  - |
    if [[ $VIM_TYPE == nvim ]]; then
      sudo apt-get install -y neovim
      nvim --version
    fi

script:
  - vint --style-problem autoload plugin
  - |
    "$VIM_TYPE" -Nu <(cat << VIMRC
    filetype off
    set rtp+=vader.vim
    set rtp+=.
    set rtp+=after
    filetype plugin indent on
    VIMRC
    ) -c 'Vader! test/*' > /dev/null
